# This config is 'lowered' to run reasonable in Kaggle (T4, 15GB VRAM)
# The values are matched when relevant to configs/rgbd/replica/base_config.yaml

Results:
  save_results: True
  save_dir: "results"
  save_trj: True
  save_trj_kf_intv: 10
  use_gui: True
  eval_rendering: False
  use_wandb: False

Dataset:
  type: 'replica'
  sensor_type: 'monocular'
  pcd_downsample: 128
  pcd_downsample_init: 64
  adaptive_pointsize: True
  point_size: 0.05 # same for replica RGB-D
  Calibration:
    fx: 600.0
    fy: 600.0
    cx: 599.5
    cy: 339.5
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1200
    height: 680
    depth_scale: 6553.5
    distorted: False

Training:
  init_itr_num: 600
  init_gaussian_update: 100
  init_gaussian_reset: 400
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  tracking_itr_num: 60
  mapping_itr_num: 100
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 1000
  size_threshold: 20
  kf_interval: 8
  window_size: 5
  pose_window: 2
  edge_threshold: 1.1 # keep low for monocular
  rgb_boundary_threshold: 0.01

  kf_translation: 0.15
  kf_min_translation: 0.10
  kf_overlap: 0.8
  kf_cutoff: 0.3
  prune_mode: 'slam'
  single_thread: True
  spherical_harmonics: False

  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001

opt_params:
  iterations: 30000
  position_lr_init: 0.0016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 150
  opacity_reset_interval: 2000
  densify_from_iter: 500
  densify_until_iter: 12000
  densify_grad_threshold: 0.0004

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False

shape:
  force_isotropic: False
