inherit_from: "configs/mono/tum/base_config.yaml"

Results:
  eval_rendering: True
  use_gui: False

Dataset:
  dataset_path: "datasets/MLCV_Chair_2/"
  num_frames: -1

  Calibration:
    fx: 525.0
    fy: 525.0
    cx: 319.5
    cy: 239.5
    
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: False
    
    width: 640
    height: 480

Experiment:
  lambda_iso: 10

shape:
  force_isotropic: False